# ASP.NET Core
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: BuildpacksInstaller@1
  inputs:
    buildpacksVersion: '0.16.0'
- task: BuildpacksTask@1
  inputs:
    command: 'build'
    imageName: 'gcr.io/idoflatow-sm-demos/pricingapp:v1'
    builder: 'gcr.io/buildpacks/builder'
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: gcr-connection
- task: Docker@2
  displayName: 'Push image'
  inputs:
    command: push
    containerRegistry: gcr-connection
    container: pricingapp
    repository: idoflatow-sm-demos/pricingapp
    tags: v1