# ASP.NET Core
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: BuildpacksInstaller@1
  inputs:
    buildpacksVersion: '0.16.0'
- task: BuildpacksTask@1
  inputs:
    command: 'build'
    imageName: 'dotnet-buildpack'
    builder: 'gcr.io/buildpacks/builder'
